name: streamlit-modeling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - arviz=0.20.0=pyhd8ed1ab_1
  - bambi=0.15.0=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - plotly=5.24.1=pyhd8ed1ab_1
  - xarray=2024.11.0=pyhd8ed1ab_0
  - zarr=2.18.4=pyhd8ed1ab_0

